
# Project names should contain only lowercase characters and underscores
name: 'currencies'
config-version: 2
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'my-bigquery-db'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
log-path: '/tmp/dbt_logs'
target-path: '/tmp/target'  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - 'dbt_packages'


# Variables


# Configuring quoting & query comment
quoting:
  database: true # translates to gcp project
  identifier: true
  schema: true # translates to gcp dataset

query-comment:
  job-label: true

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  currencies:
    # Applies to all files under models/example/
    prp:
      +dataset: prp
      +materialized: table
    ods:
      +dataset: "{{ env_var('DATASET_NAME_ODS') }}"
      +materialized: table
    prs:
      +database: "{{ env_var('FRONT_PROJECT_ID') }}"
      +materialized: table
      macro:
        +dataset: macro
      
# Configuring seeds
seeds:
  currencies:
    +dataset: stg     